# Set the dynamixel id for controller
agent_pan:
  ID: 1
  Return_Delay_Time: 0
agent_tilt:
  ID: 2
  Return_Delay_Time: 0
# Set the dynamixel id for agent
control_pan:
  ID: 3
  Return_Delay_Time: 0
