# linux port and AX-12A baud rate
usb_port: "/dev/ttyUSB0"
dxl_baud_rate: 1000000

# control table addresses
addr_torque_enable: 24
addr_goal_position: 30
addr_present_position: 36
addr_speed: 32

# AX-12A min max
dxl_minimum_position_value: 0
dxl_maximum_position_value: 1023

# Protocol version
protocol_version: 1.0

# Set the dynamixel id for various joints
joint_pan:
  ID: 1
  zero_config: 512
  speed: 100
joint_tilt:
  ID: 2
  zero_config: 819
  speed: 100
joint_elbow:
  ID: 3
  zero_config: 819
  speed: 100
joint_paddle:
  ID: 4
  zero_config: 512
  speed: 100
